on:
  workflow_call:
    inputs:
      upload-artifact-key:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    name: Build with Node ${{ matrix.node-version }}
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        working-directory: ./frontend
        run: npm ci --legacy-peer-deps
      - name: Build
        working-directory: ./frontend
        run: npm run build --if-present
      - name: Test
        working-directory: ./frontend
        run: npm test 
      - name: Artifact build folder for deploy
        if: ${{ inputs.upload-artifact-key != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.upload-artifact-key }}
          path: frontend/build/