name: Reusable workflow to build react app using npm
on:
  workflow_call:
    inputs:
      upload-artifact-key:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    name: Build with Node ${{ matrix.node-version }}
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        working-directory: ./frontend
        run: npm ci --legacy-peer-deps
      - name: Build
        working-directory: ./frontend
        run: npm run build --if-present
      - name: Test
        working-directory: ./frontend
        run: npm test 
      - name: Artifact build folder for deploy
        if: ${{ inputs.upload-artifact-key != '' }}
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: ${{ inputs.upload-artifact-key }}
          path: frontend/build/