name: Reusable workflow to build maven project
on:
  workflow_call:
    inputs:
      upload-artifact-key:
        required: false
        type: string
      app-name:
        required: false
        type: string
        default: "pr-build"
jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          java-version: [11.0.x]
      name: Build with Java ${{ matrix.java-version }}
      env:
        OS: ${{ matrix.os }}
        JAVA_VERSION: ${{ matrix.java-version }}
        FN_APP_NAME: ${{ inputs.app-name }}
      steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Setup Java
        uses: actions/setup-java@215b7e5f829ab9cac114c149667e57dc1b70b4bc # v2.5.2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Build and Test
        working-directory: ./backend/FaceApp
        run: mvn clean install -DappName=$FN_APP_NAME
      - name: Artifact folder for deploy
        if: ${{ inputs.upload-artifact-key != '' }}
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: app
          path: .

