name: Build frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "!frontend/bicep/**"

jobs:
  build-react-app:
    uses: ./.github/workflows/build-react-app.yml