name: Reusable workflow to build multiple bicep files
on:
  workflow_call:
    inputs:
      bicep-files:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(inputs.bicep-files) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate ${{ inputs.bicep-file }}
        uses: azure/CLI@9eb25b8360668fb0ecbafa808d40e2197b2f5f52 # v3.0.0
        with:
          inlineScript: |
            az bicep upgrade
            az bicep build --file ${{ matrix.file }}
