name: Build frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - "!backend/bicep/**"

jobs:
  build-react-app:
    uses: ./.github/workflows/build-maven-project.yml