name: Build backend

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/build-backend.yml"
      - ".github/workflows/build-maven-project.yml"
      - "!backend/bicep/**"

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-java-app:
    uses: ./.github/workflows/build-maven-project.yml

  dependabot-approve-merge:
    needs: build-java-app
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@8348ea7f5d949b08c7f125a44b569c9626b05db3 # v1.7.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
      - name: auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}