name: Build frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/build-frontend.yml"
      - ".github/workflows/build-react-app.yml"
      - "!frontend/bicep/**"

jobs:
  build-react-app:
    uses: ./.github/workflows/build-react-app.yml

  dependabot-approve-merge:
    needs: build-react-app
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest   
    permissions:
      pull_requests: write
    steps:
      - name: Approve a PR
        run: |
          gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_URL"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}