name: Build and Deploy Frontend to Azure Storage

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**
  workflow_dispatch:

env:
  AZURE_REGION: ${{ vars.AZURE_REGION }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}

permissions:
      id-token: write
      contents: read

jobs:
  build:
    environment: ${{ vars.DEFAULT_ENVIRONMENT }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [19.x]
    name: Build with Node ${{ matrix.node-version }}
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      working-directory: ./frontend
      run: npm ci --legacy-peer-deps
    - name: Build
      working-directory: ./frontend
      run: npm run build --if-present
    - name: Test
      working-directory: ./frontend
      run: npm test
      
    - name: Artifact build folder for deploy
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: frontend/build/
  deploy:
    environment: ${{ vars.DEFAULT_ENVIRONMENT }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to azure storage
    steps:
    - name: Download artifact for deploy
      uses: actions/download-artifact@v3
      with:
        name: website
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Get frontend storage name
      uses: azure/CLI@v1
      with:
        inlineScript: |
          FRONTEND_STORAGE=$(az storage account list -g ${{ env.RESOURCE_GROUP }} -o tsv --query "[?starts_with(name, 'frontendapp')]|[0].name")
          echo "FRONTEND_STORAGE=$FRONTEND_STORAGE" >> $GITHUB_ENV
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            echo Deploying to storage account $FRONTEND_STORAGE
            az storage blob upload-batch --account-name $FRONTEND_STORAGE --auth-mode key -d '$web' -s . --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az config set defaults.location=$AZURE_REGION defaults.group=$RESOURCE_GROUP
            az cdn endpoint purge --content-paths / --ids $(az cdn endpoint list --profile-name $(az cdn profile list -o tsv --query [0].name) -o tsv --query [0].id)
    - name: logout
      run: |
            az logout
      if: always()
