name: Build frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/build-frontend.yml"
      - ".github/workflows/build-react-app.yml"
      - "!frontend/bicep/**"

concurrency:
  group: frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-react-app:
    uses: ./.github/workflows/build-react-app.yml

  dependabot-approve-merge:
    needs: build-react-app
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
      - name: auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}