name: Deploy frontend infrastructure

on:
  push:
    branches:
      - main
    paths:
      - frontend/bicep/**
  workflow_dispatch:

env:
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  DNS_ZONE: ${{ vars.DNS_ZONE }}
  AZURE_REGION: ${{ vars.AZURE_REGION }}
  BICEP_FILE_PATH: frontend/bicep
  BICEP_FILE_NAME: main

permissions:
      id-token: write
      contents: read

jobs:
  frontend-infra-deployment:
    environment: ${{ vars.DEFAULT_ENVIRONMENT }}
    runs-on: ubuntu-latest
    name: Build and Deploy frontend infrastructure bicep templates
    steps:
    - name: Checkout
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Azure login
      uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Set default region and resource group for cli and register CDN
      uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
      with:
        inlineScript: |
          az config set defaults.location=${{ env.AZURE_REGION }} defaults.group=${{ env.RESOURCE_GROUP }}
          az provider register --namespace Microsoft.Cdn
    - name: Validate frontend infra bicep file  ${{ env.BICEP_FILE_PATH }}/${{ env.BICEP_FILE_NAME }}.bicep
      uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
      with:
        inlineScript: |
          az deployment group validate --template-file ./${{ env.BICEP_FILE_PATH }}/${{ env.BICEP_FILE_NAME }}.bicep -p dnsZoneName=${{ env.DNS_ZONE }}
          az bicep upgrade
          az bicep build --file ./${{ env.BICEP_FILE_PATH }}/${{ env.BICEP_FILE_NAME }}.bicep
    - name: Deploy frontend infrastructure
      id: frontendInfraDeployment
      uses: azure/arm-deploy@65ae74fb7aec7c680c88ef456811f353adae4d06 # v1.0.9
      with:
        deploymentName: 'via-github-frontend-infra-${{ github.run_number }}'
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        region: ${{ env.AZURE_REGION }}
        template: ./${{ env.BICEP_FILE_PATH }}/${{ env.BICEP_FILE_NAME }}.json  # Set this to the location of your template file
        parameters: dnsZoneName=${{ env.DNS_ZONE }}
