# workflow to label new open issues and assign them to a specific user in different jobs

name: Label new issues and assign to user

on:
  issues:
    types: [opened]

env:
  ISSUE_OWNER: pankajagrawal16

permissions:
  issues: write

jobs:
    label:
        runs-on: ubuntu-latest
        steps:
            - name: Label issue
              uses: actions/github-script@v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      github.issues.addLabels({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          labels: ['triage']
                        });

    assing-user:
        runs-on: ubuntu-latest
        steps:
          - name: Assign issue to a user
            uses: actions/github-script@v4
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                github.issues.addAssignees({
                  issue_number: context.issue.number,
                  assignees: [process.env.ISSUE_OWNER],
                  owner: context.repo.owner,
                  repo: context.repo.repo
                });

