# Label newly opened issues with label called triage

name: Label Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
    triage:
        runs-on: ubuntu-latest
        steps:
          - name: Label issue
            uses: actions/github-script@v4
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                github.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['triage']
                })

     # assign newly opened issues to the person who opened them
    assign:
        runs-on: ubuntu-
        steps:
          - name: Assign issue
            uses: actions/github-script@v4
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                github.issues.addAssignees({
                  issue_number: context.issue.number,
                  assignees: [context.payload.issue.user.login]
                })