# workflow to label issues when opened and assign an owner defined as environment variable
# labelling issues and assigning owner are two different jobs. First job labels the issue and second job assigns the owner

name: Label Issues and Assign Owner

on:
  issues:
    types: [opened]

env:
  # read from repository variable
    ISSUE_OWNER: ${{ vars.ISSUE_OWNER }}

permissions:
    issues: write

jobs:
    label:
        runs-on: ubuntu-latest
        steps:
            - name: Label issue
              uses: actions/github-script@v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      github.issues.addLabels({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          labels: ['triage']
                        });

    assign-user:
        runs-on: ubuntu-latest
        needs: label
        steps:
          - name: Assign issue to a user
            uses: actions/github-script@v4
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                github.issues.addAssignees({
                  issue_number: context.issue.number,
                  assignees: [process.env.ISSUE_OWNER],
                  owner: context.repo.owner,
                  repo: context.repo.repo
                });
